description: null
exclude:
- code
- node_modules
highlighter: rouge
input: GFM
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
title: Christopher Doyle
top_track:
  artist: Collective Soul
  name: December
  playcount: 33
url: https://christopherdoyle.github.io/
