description: null
exclude:
- code
- node_modules
highlighter: rouge
input: GFM
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
title: Christopher Doyle
top_track:
  artist: The Smiths
  name: That Joke Isn't Funny Anymore
  playcount: 11
url: https://christopherdoyle.github.io/
