description: null
exclude:
- code
- node_modules
highlighter: rouge
input: GFM
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
title: Christopher Doyle
top_track:
  artist: Gabriele Motta
  name: Gomu Gomu No Bazooka - From "One Piece", Metal Version
  playcount: 14
url: https://christopherdoyle.github.io/
